###################################################################

# Created by write_sdc on Mon Aug 31 22:36:48 2026

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -max_library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -min scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c -min_library scmetro_tsmc_cl013g_rvt_ff_1p32v_m40c
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[31]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[30]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[29]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[28]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[27]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[26]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[25]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[24]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[23]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[22]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[21]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[20]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[19]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[18]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[17]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[16]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[15]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[14]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[13]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[12]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[11]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[10]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[9]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[8]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[7]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[6]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[5]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[4]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxsdata[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxscntl[5]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxscntl[4]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxscntl[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxscntl[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxscntl[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_cxscntl[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports i_cxsvalid]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports i_cxsactivereq]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports i_cxs_cxscrdgnt]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports i_cxs_cxsactiveack]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports i_app_rd_en]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_app_rd_address[8]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_app_rd_address[7]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_app_rd_address[6]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_app_rd_address[5]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_app_rd_address[4]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_app_rd_address[3]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_app_rd_address[2]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_app_rd_address[1]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports {i_app_rd_address[0]}]
set_driving_cell -lib_cell BUFX2M -library scmetro_tsmc_cl013g_rvt_ss_1p08v_125c -pin Y [get_ports i_app_ack]
set_load -pin_load 0.5 [get_ports o_cxscrdgnt]
set_load -pin_load 0.5 [get_ports o_cxsactiveack]
set_load -pin_load 0.5 [get_ports o_CXSVALID]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[31]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[30]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[29]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[28]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[27]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[26]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[25]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[24]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[23]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[22]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[21]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[20]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[19]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[18]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[17]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[16]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[15]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[14]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[13]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[12]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[11]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[10]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[9]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[8]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[7]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[6]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[5]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[4]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[3]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[2]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[1]}]
set_load -pin_load 0.5 [get_ports {o_CXSDATA[0]}]
set_load -pin_load 0.5 [get_ports {o_CXSCNTL[5]}]
set_load -pin_load 0.5 [get_ports {o_CXSCNTL[4]}]
set_load -pin_load 0.5 [get_ports {o_CXSCNTL[3]}]
set_load -pin_load 0.5 [get_ports {o_CXSCNTL[2]}]
set_load -pin_load 0.5 [get_ports {o_CXSCNTL[1]}]
set_load -pin_load 0.5 [get_ports {o_CXSCNTL[0]}]
set_load -pin_load 0.5 [get_ports o_CXSACTIVEREQ]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[16]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[15]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[14]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[13]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[12]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[11]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[10]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[9]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[8]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[7]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[6]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[5]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[4]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[3]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[2]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[1]}]
set_load -pin_load 0.5 [get_ports {o_app_rd_data[0]}]
create_clock [get_ports i_cxs_clk]  -name CXS_CLK  -period 27.027  -waveform {0 13.5135}
set_clock_latency 0  [get_clocks CXS_CLK]
set_clock_uncertainty -setup 0.25  [get_clocks CXS_CLK]
set_clock_uncertainty -hold 0.05  [get_clocks CXS_CLK]
set_clock_transition -max -rise 0.1 [get_clocks CXS_CLK]
set_clock_transition -min -rise 0.1 [get_clocks CXS_CLK]
set_clock_transition -max -fall 0.1 [get_clocks CXS_CLK]
set_clock_transition -min -fall 0.1 [get_clocks CXS_CLK]
create_clock [get_ports i_system_clk]  -name SYSTEM_CLK  -period 40  -waveform {0 20}
set_clock_latency 0  [get_clocks SYSTEM_CLK]
set_clock_uncertainty -setup 0.25  [get_clocks SYSTEM_CLK]
set_clock_uncertainty -hold 0.05  [get_clocks SYSTEM_CLK]
set_clock_transition -max -rise 0.1 [get_clocks SYSTEM_CLK]
set_clock_transition -min -rise 0.1 [get_clocks SYSTEM_CLK]
set_clock_transition -max -fall 0.1 [get_clocks SYSTEM_CLK]
set_clock_transition -min -fall 0.1 [get_clocks SYSTEM_CLK]
group_path -name CXS_IN  -from [list [get_ports {i_cxsdata[31]}] [get_ports {i_cxsdata[30]}] [get_ports {i_cxsdata[29]}] [get_ports {i_cxsdata[28]}] [get_ports {i_cxsdata[27]}] [get_ports {i_cxsdata[26]}] [get_ports {i_cxsdata[25]}] [get_ports {i_cxsdata[24]}] [get_ports {i_cxsdata[23]}] [get_ports {i_cxsdata[22]}] [get_ports {i_cxsdata[21]}] [get_ports {i_cxsdata[20]}] [get_ports {i_cxsdata[19]}] [get_ports {i_cxsdata[18]}] [get_ports {i_cxsdata[17]}] [get_ports {i_cxsdata[16]}] [get_ports {i_cxsdata[15]}] [get_ports {i_cxsdata[14]}] [get_ports {i_cxsdata[13]}] [get_ports {i_cxsdata[12]}] [get_ports {i_cxsdata[11]}] [get_ports {i_cxsdata[10]}] [get_ports {i_cxsdata[9]}] [get_ports {i_cxsdata[8]}] [get_ports {i_cxsdata[7]}] [get_ports {i_cxsdata[6]}] [get_ports {i_cxsdata[5]}] [get_ports {i_cxsdata[4]}] [get_ports {i_cxsdata[3]}] [get_ports {i_cxsdata[2]}] [get_ports {i_cxsdata[1]}] [get_ports {i_cxsdata[0]}]]
group_path -name CXS_OUT  -to [list [get_ports {o_CXSDATA[31]}] [get_ports {o_CXSDATA[30]}] [get_ports {o_CXSDATA[29]}] [get_ports {o_CXSDATA[28]}] [get_ports {o_CXSDATA[27]}] [get_ports {o_CXSDATA[26]}] [get_ports {o_CXSDATA[25]}] [get_ports {o_CXSDATA[24]}] [get_ports {o_CXSDATA[23]}] [get_ports {o_CXSDATA[22]}] [get_ports {o_CXSDATA[21]}] [get_ports {o_CXSDATA[20]}] [get_ports {o_CXSDATA[19]}] [get_ports {o_CXSDATA[18]}] [get_ports {o_CXSDATA[17]}] [get_ports {o_CXSDATA[16]}] [get_ports {o_CXSDATA[15]}] [get_ports {o_CXSDATA[14]}] [get_ports {o_CXSDATA[13]}] [get_ports {o_CXSDATA[12]}] [get_ports {o_CXSDATA[11]}] [get_ports {o_CXSDATA[10]}] [get_ports {o_CXSDATA[9]}] [get_ports {o_CXSDATA[8]}] [get_ports {o_CXSDATA[7]}] [get_ports {o_CXSDATA[6]}] [get_ports {o_CXSDATA[5]}] [get_ports {o_CXSDATA[4]}] [get_ports {o_CXSDATA[3]}] [get_ports {o_CXSDATA[2]}] [get_ports {o_CXSDATA[1]}] [get_ports {o_CXSDATA[0]}]]
group_path -name INOUT  -from [list [get_ports i_rst_n] [get_ports i_cxs_clk] [get_ports {i_cxsdata[31]}] [get_ports {i_cxsdata[30]}] [get_ports {i_cxsdata[29]}] [get_ports {i_cxsdata[28]}] [get_ports {i_cxsdata[27]}] [get_ports {i_cxsdata[26]}] [get_ports {i_cxsdata[25]}] [get_ports {i_cxsdata[24]}] [get_ports {i_cxsdata[23]}] [get_ports {i_cxsdata[22]}] [get_ports {i_cxsdata[21]}] [get_ports {i_cxsdata[20]}] [get_ports {i_cxsdata[19]}] [get_ports {i_cxsdata[18]}] [get_ports {i_cxsdata[17]}] [get_ports {i_cxsdata[16]}] [get_ports {i_cxsdata[15]}] [get_ports {i_cxsdata[14]}] [get_ports {i_cxsdata[13]}] [get_ports {i_cxsdata[12]}] [get_ports {i_cxsdata[11]}] [get_ports {i_cxsdata[10]}] [get_ports {i_cxsdata[9]}] [get_ports {i_cxsdata[8]}] [get_ports {i_cxsdata[7]}] [get_ports {i_cxsdata[6]}] [get_ports {i_cxsdata[5]}] [get_ports {i_cxsdata[4]}] [get_ports {i_cxsdata[3]}] [get_ports {i_cxsdata[2]}] [get_ports {i_cxsdata[1]}] [get_ports {i_cxsdata[0]}] [get_ports {i_cxscntl[5]}] [get_ports {i_cxscntl[4]}] [get_ports {i_cxscntl[3]}] [get_ports {i_cxscntl[2]}] [get_ports {i_cxscntl[1]}] [get_ports {i_cxscntl[0]}] [get_ports i_cxsvalid] [get_ports i_cxsactivereq] [get_ports i_cxscrdrtn] [get_ports i_cxs_cxscrdgnt] [get_ports i_cxs_cxsactiveack] [get_ports i_system_clk] [get_ports i_app_rd_en] [get_ports {i_app_rd_address[8]}] [get_ports {i_app_rd_address[7]}] [get_ports {i_app_rd_address[6]}] [get_ports {i_app_rd_address[5]}] [get_ports {i_app_rd_address[4]}] [get_ports {i_app_rd_address[3]}] [get_ports {i_app_rd_address[2]}] [get_ports {i_app_rd_address[1]}] [get_ports {i_app_rd_address[0]}] [get_ports i_app_ack]]  -to [list [get_ports o_cxscrdgnt] [get_ports o_cxsactiveack] [get_ports o_CXSVALID] [get_ports {o_CXSDATA[31]}] [get_ports {o_CXSDATA[30]}] [get_ports {o_CXSDATA[29]}] [get_ports {o_CXSDATA[28]}] [get_ports {o_CXSDATA[27]}] [get_ports {o_CXSDATA[26]}] [get_ports {o_CXSDATA[25]}] [get_ports {o_CXSDATA[24]}] [get_ports {o_CXSDATA[23]}] [get_ports {o_CXSDATA[22]}] [get_ports {o_CXSDATA[21]}] [get_ports {o_CXSDATA[20]}] [get_ports {o_CXSDATA[19]}] [get_ports {o_CXSDATA[18]}] [get_ports {o_CXSDATA[17]}] [get_ports {o_CXSDATA[16]}] [get_ports {o_CXSDATA[15]}] [get_ports {o_CXSDATA[14]}] [get_ports {o_CXSDATA[13]}] [get_ports {o_CXSDATA[12]}] [get_ports {o_CXSDATA[11]}] [get_ports {o_CXSDATA[10]}] [get_ports {o_CXSDATA[9]}] [get_ports {o_CXSDATA[8]}] [get_ports {o_CXSDATA[7]}] [get_ports {o_CXSDATA[6]}] [get_ports {o_CXSDATA[5]}] [get_ports {o_CXSDATA[4]}] [get_ports {o_CXSDATA[3]}] [get_ports {o_CXSDATA[2]}] [get_ports {o_CXSDATA[1]}] [get_ports {o_CXSDATA[0]}] [get_ports {o_CXSCNTL[5]}] [get_ports {o_CXSCNTL[4]}] [get_ports {o_CXSCNTL[3]}] [get_ports {o_CXSCNTL[2]}] [get_ports {o_CXSCNTL[1]}] [get_ports {o_CXSCNTL[0]}] [get_ports o_CXSACTIVEREQ] [get_ports {o_app_rd_data[16]}] [get_ports {o_app_rd_data[15]}] [get_ports {o_app_rd_data[14]}] [get_ports {o_app_rd_data[13]}] [get_ports {o_app_rd_data[12]}] [get_ports {o_app_rd_data[11]}] [get_ports {o_app_rd_data[10]}] [get_ports {o_app_rd_data[9]}] [get_ports {o_app_rd_data[8]}] [get_ports {o_app_rd_data[7]}] [get_ports {o_app_rd_data[6]}] [get_ports {o_app_rd_data[5]}] [get_ports {o_app_rd_data[4]}] [get_ports {o_app_rd_data[3]}] [get_ports {o_app_rd_data[2]}] [get_ports {o_app_rd_data[1]}] [get_ports {o_app_rd_data[0]}]]
group_path -name SYSTEM_IN  -from [get_ports i_app_rd_en]
group_path -name SYSTEM_OUT  -to [list [get_ports {o_app_rd_data[16]}] [get_ports {o_app_rd_data[15]}] [get_ports {o_app_rd_data[14]}] [get_ports {o_app_rd_data[13]}] [get_ports {o_app_rd_data[12]}] [get_ports {o_app_rd_data[11]}] [get_ports {o_app_rd_data[10]}] [get_ports {o_app_rd_data[9]}] [get_ports {o_app_rd_data[8]}] [get_ports {o_app_rd_data[7]}] [get_ports {o_app_rd_data[6]}] [get_ports {o_app_rd_data[5]}] [get_ports {o_app_rd_data[4]}] [get_ports {o_app_rd_data[3]}] [get_ports {o_app_rd_data[2]}] [get_ports {o_app_rd_data[1]}] [get_ports {o_app_rd_data[0]}]]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[31]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[30]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[29]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[28]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[27]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[26]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[25]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[24]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[23]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[22]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[21]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[20]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[19]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[18]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[17]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[16]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[15]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[14]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[13]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[12]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[11]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[10]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[9]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[8]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[7]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[6]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[5]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[4]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[3]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[2]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[1]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxsdata[0]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxscntl[5]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxscntl[4]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxscntl[3]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxscntl[2]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxscntl[1]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports {i_cxscntl[0]}]
set_input_delay -clock CXS_CLK  8.1081  [get_ports i_cxsvalid]
set_input_delay -clock CXS_CLK  8.1081  [get_ports i_cxsactivereq]
set_input_delay -clock CXS_CLK  8.1081  [get_ports i_cxscrdrtn]
set_input_delay -clock CXS_CLK  8.1081  [get_ports i_cxs_cxscrdgnt]
set_input_delay -clock CXS_CLK  8.1081  [get_ports i_cxs_cxsactiveack]
set_input_delay -clock SYSTEM_CLK  12  [get_ports i_app_rd_en]
set_input_delay -clock SYSTEM_CLK  12  [get_ports {i_app_rd_address[8]}]
set_input_delay -clock SYSTEM_CLK  12  [get_ports {i_app_rd_address[7]}]
set_input_delay -clock SYSTEM_CLK  12  [get_ports {i_app_rd_address[6]}]
set_input_delay -clock SYSTEM_CLK  12  [get_ports {i_app_rd_address[5]}]
set_input_delay -clock SYSTEM_CLK  12  [get_ports {i_app_rd_address[4]}]
set_input_delay -clock SYSTEM_CLK  12  [get_ports {i_app_rd_address[3]}]
set_input_delay -clock SYSTEM_CLK  12  [get_ports {i_app_rd_address[2]}]
set_input_delay -clock SYSTEM_CLK  12  [get_ports {i_app_rd_address[1]}]
set_input_delay -clock SYSTEM_CLK  12  [get_ports {i_app_rd_address[0]}]
set_input_delay -clock SYSTEM_CLK  12  [get_ports i_app_ack]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[31]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[30]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[29]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[28]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[27]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[26]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[25]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[24]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[23]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[22]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[21]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[20]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[19]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[18]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[17]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[16]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[15]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[14]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[13]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[12]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[11]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[10]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[9]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[8]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[7]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[6]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[5]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[4]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[3]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[2]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[1]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSDATA[0]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports o_cxscrdgnt]
set_output_delay -clock CXS_CLK  8.1081  [get_ports o_cxsactiveack]
set_output_delay -clock CXS_CLK  8.1081  [get_ports o_CXSVALID]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSCNTL[5]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSCNTL[4]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSCNTL[3]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSCNTL[2]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSCNTL[1]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports {o_CXSCNTL[0]}]
set_output_delay -clock CXS_CLK  8.1081  [get_ports o_CXSACTIVEREQ]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[16]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[15]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[14]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[13]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[12]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[11]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[10]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[9]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[8]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[7]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[6]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[5]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[4]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[3]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[2]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[1]}]
set_output_delay -clock SYSTEM_CLK  12  [get_ports {o_app_rd_data[0]}]
set_clock_groups -asynchronous -name CXS_CLK_1 -group [get_clocks CXS_CLK] -group [get_clocks SYSTEM_CLK]
